config/routes.rb
HotelCommerce::Application.routes.draw do

  resources :receipts
  resources :users
  
  resources :deals do
    resources :receipts
  end
  
  resources :hotels do
    resources :deals do
      resources :receipts
    end
  end
  
  resources :providers do
    resources :deals do
      resources :receipts
    end
  end
  
  
  

end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  attr_accessible :barcode, :buyer_name, :buyer_telephone, :code, :used
  belongs_to :deal, :dependent => :destroy
end

app/controllers/receipt_controller.rb
class ReceiptController < ApplicationController
  def used:boolean
  end

  def buyer_name:string
  end

  def buyer_telephone:string
  end

  def barcode:string
  end

  def code:string
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @receipts }
    end
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(params[:receipt])

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/receipt_helper.rb
module ReceiptHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_for(@receipt) do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :used %><br />
    <%= f.check_box :used %>
  </div>
  <div class="field">
    <%= f.label :buyer_name %><br />
    <%= f.text_field :buyer_name %>
  </div>
  <div class="field">
    <%= f.label :buyer_telephone %><br />
    <%= f.text_field :buyer_telephone %>
  </div>
  <div class="field">
    <%= f.label :barcode %><br />
    <%= f.text_field :barcode %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<h1>Listing receipts</h1>

<table>
  <tr>
    <th>Used</th>
    <th>Buyer name</th>
    <th>Buyer telephone</th>
    <th>Barcode</th>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @receipts.each do |receipt| %>
  <tr>
    <td><%= receipt.used %></td>
    <td><%= receipt.buyer_name %></td>
    <td><%= receipt.buyer_telephone %></td>
    <td><%= receipt.barcode %></td>
    <td><%= receipt.code %></td>
    <td><%= link_to 'Show', receipt %></td>
    <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
    <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Used:</b>
  <%= @receipt.used %>
</p>

<p>
  <b>Buyer name:</b>
  <%= @receipt.buyer_name %>
</p>

<p>
  <b>Buyer telephone:</b>
  <%= @receipt.buyer_telephone %>
</p>

<p>
  <b>Barcode:</b>
  <%= @receipt.barcode %>
</p>

<p>
  <b>Code:</b>
  <%= @receipt.code %>
</p>


<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>